name: "KiCad CI/CD for RS232 DE-9 to EIA-561 RJ45 adapters (norm)"

# Controls when the action will run. Triggers the workflow on push or pull
# request events but only for the master branch
on:
  push:
    paths:
      - 'norm/*.kicad_sch'
      - 'norm/*.kicad_pcb'
      - 'norm/*.kibot.yaml'
      - '.github/workflows/norm.yml'
  pull_request:
    paths:
      - 'norm/*.kicad_sch'
      - 'norm/*.kicad_pcb'
      - 'norm/*.kibot.yaml'
      - '.github/workflows/norm.yml'

# A workflow run is made up of one or more jobs that can run sequentially or
# in parallel
jobs:
  Fabrication:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: INTI-CMNB/KiBot@v2_k10
      with:
        # Required - kibot config file
        config: norm/rack-ser-adapter.kibot.yaml
        # optional - prefix to output defined in config
        dir: 'Fabrication-norm'
        # optional - schematic file
        schema: 'norm/rack-ser-adapter.kicad_sch'
        # optional - PCB design file
        board: 'norm/rack-ser-adapter.kicad_pcb'
        verbose: 1

    - name: Create downloads directory
      run: mkdir downloads-norm

    - name: Fix ownership
      run: sudo chown $(whoami) Fabrication-norm

    - name: Gerber Archive
      uses: thedoctor0/zip-release@master
      with:
        filename: 'Fabrication-norm/gerber.zip'
        path: 'Fabrication-norm/Gerbers'

    - name: Downloads zip Archive
      uses: thedoctor0/zip-release@master
      with:
        filename: 'downloads-norm/fabrication.zip'
        path: 'Fabrication-norm'

    - name: Downloads tar Archive
      uses: thedoctor0/zip-release@master
      with:
        filename: 'downloads-norm/fabrication.tar.gz'
        path: 'Fabrication-norm'
        type: tar

    - name: Retrieve results
      if: ${{ always() }}
      uses: actions/upload-artifact@v7
      with:
        name: Fabrication-norm
        path: |
          Fabrication-norm/
        if-no-files-found: warn

    - name: Deploy Fabrication
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: Fabrication-norm
        target-folder: Fabrication-norm

    - name: Deploy Downloads
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: downloads-norm
        target-folder: downloads-norm
